// <auto-generated />
namespace TelerikAcademy.AutoDealer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class image_Urls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(image_Urls));
        
        string IMigrationMetadata.Id
        {
            get { return "201710120656078_image_Urls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
