// <auto-generated />
namespace TelerikAcademy.AutoDealer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CarOwnerRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarOwnerRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201710120624457_CarOwnerRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
