// <auto-generated />
namespace TelerikAcademy.AutoDealer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CarValidationChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarValidationChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201710112243044_CarValidationChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
